### ISSUE TITLE
Incrementing ordered list, compliance with `mdformat` `--number` option

### ISSUE THREAD

**Issue by CBroz1** [KyleKing/mdformat-mkdocs#12]
Thanks for all your work here! It's been super helpful for indenting. 

I'm curious about the motivation behind enforcing `1.` when `mdformat` accepts an arg to increment. Maybe it a decision made before `mdformat` added the arg?

<details>
<summary>With the following pre-commit setup, my ordered lists increment</summary>

```yaml
repos:
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        name: Format Markdown
        entry: mdformat # Executable to run, with fixed options
        language: python
        types: [markdown]
        args: ["--number"]
```
</details>

<details>
<summary>With `mdformat-mkdocs` added, it looks like `mdformat` is ignoring the provided arg, causing confusion.</summary>

```yaml
repos:
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        name: Format Markdown
        entry: mdformat # Executable to run, with fixed options
        language: python
        types: [markdown]
        args: ["--number"]
        additional_dependencies:
          - mdformat-mkdocs
```
</details>
