### ISSUE TITLE
Render conflict w/ latest mdformat & mdformat-mkdocs

### ISSUE THREAD

**Issue by MrMino** [KyleKing/mdformat-mkdocs#24]
The following pre-commit config and test file crashes `mdformat` when run via `pre-commit run --all`:

`.pre-commit-config.yaml`

```yaml
repos:
  - repo: https://github.com/executablebooks/mdformat.git
    rev: 0.7.17
    hooks:
    -   id: mdformat
        additional_dependencies:
          - mdformat-mkdocs>=2.0.9
```

`test.md`

```
0. xyz
```

Repro:

```bash
mkcd /tmp/repro

> .pre-commit-config.yaml << EOF
repos:
  - repo: https://github.com/executablebooks/mdformat.git
    rev: 0.7.17
    hooks:
    -   id: mdformat
        additional_dependencies:
          - mdformat-mkdocs>=2.0.9
EOF
 
echo "0. xyz" > test.md
git init
git add .
pre-commit run --all
```

Error message:

```
mdformat.................................................................Failed
- hook id: mdformat
- exit code: 1

Error: Could not format "/tmp/repro/test.md".

The formatted Markdown renders to different HTML than the input Markdown. This
is likely a bug in mdformat. Please create an issue report here, including the
input Markdown: https://github.com/executablebooks/mdformat/issues
```
