### ISSUE TITLE
Mardown anchors support

### ISSUE THREAD

**Issue by gospodima** [KyleKing/mdformat-mkdocs#25]
Hello,

thank you for maintaining this library!

I am using [markdown anchors](https://mkdocstrings.github.io/autorefs/#markdown-anchors) from [autorefs](https://mkdocstrings.github.io/autorefs/) plugin.

mdformat changes `[](){#some-anchor-name}` to `[](<>){#some-anchor-name}`. Is it possible to disable such behaviour?

.pre-commit-config.yaml:

```yaml
repos:
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.17
  hooks:
    - id: mdformat
      additional_dependencies:
        - mdformat-mkdocs[recommended]>=2.0.0
      args: [--wrap=88, --number]
```
