### ISSUE TITLE
Error formatting numbered lists with code snippets

### ISSUE THREAD

**Issue by pelson** [KyleKing/mdformat-mkdocs#35]
Given the following input:

```
# A B C

1. Test
    ```bash
    python -m pip install foo
    ```

2. Another
   For example:

    ```yaml
    repos:
      - repo: https://github.com/psf/black
        rev: v24.4
        hooks:
        - id: black
    ```
```

I get the following error:

```
The formatted Markdown renders to different HTML than the input Markdown. This
is likely a bug in mdformat. Please create an issue report here, including the
input Markdown: https://github.com/executablebooks/mdformat/issues
```

This is with the latest release from pypi.
