### ISSUE TITLE
Semantic line feeds issue in nested bullets in numbered lists

### ISSUE THREAD

**Issue by jamesbraza** [KyleKing/mdformat-mkdocs#7]
Same issue as https://github.com/KyleKing/mdformat-mkdocs/issues/4, but for nested bullets inside a list.

1. Line
   semantic line 1 (3 spaces deep)
    - Bullet (4 spaces deep)
      semantic line 2 (6 spaces deep)

I believe `mdformat-mkdocs==1.0.2` is impacting the second semantic line feed.

---

I have `prettier` (`.prettierrc.toml`: `tabWidth = 4`) and `mdformat`, together in `pre-commit`:

```yaml
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.0.0
      hooks:
          - id: prettier
    - repo: https://github.com/executablebooks/mdformat
      rev: 0.7.16
      hooks:
          - id: mdformat
            additional_dependencies:
                - mdformat-black
                - mdformat-footnote
                - mdformat-frontmatter
                - mdformat-gfm
                - mdformat-mkdocs>=1.0.2rc2
            args: [--align-semantic-breaks-in-numbered-lists]
```
